name: Deploy to GKE

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    container:
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode and Set up Google Cloud SDK
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project my-kubernetes-project-438008

      - name: Authenticate to GKE Cluster
        run: |
          gcloud container clusters get-credentials vector-cluster --zone us-central1-a --project my-kubernetes-project-438008

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/
