name: Deploy to GKE

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger deployments

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '420.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: my-kubernetes-project-438008  # Replace with your GCP project ID

    - name: Authenticate with GKE
      run: |
        gcloud container clusters get-credentials vector-cluster \
          --region us-central1-a \
          --project my-kubernetes-project-438008

    - name: Apply Kubernetes Configuration
      run: |
        kubectl apply -f k8s/

    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get hpa
