name: Deploy to GKE (Dockerized)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 1: Run in a Dockerized Environment with Pre-installed Tools
    - name: Deploy Using Dockerized Environment
      run: |
        docker run --rm \
          -v "$(pwd):/workspace" \
          -v "$HOME/.kube:/root/.kube" \
          -v "$HOME/.config/gcloud:/root/.config/gcloud" \
          google/cloud-sdk:latest /bin/bash -c "
            cd /workspace &&
            echo '${{ secrets.GCP_SA_KEY }}' | base64 --decode > sa-key.json &&
            gcloud auth activate-service-account --key-file=sa-key.json &&
            gcloud auth list &&
            gcloud config set project my-kubernetes-project-438008 &&
            gcloud components install gke-gcloud-auth-plugin --quiet &&
            export USE_GKE_GCLOUD_AUTH_PLUGIN=True &&
            gcloud container clusters get-credentials vector-cluster --region us-central1-a --project my-kubernetes-project-438008 &&
            kubectl apply -f k8s/ &&
            kubectl get pods &&
            kubectl get hpa
          "
