name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Write the Service Account Key from Secret
    - name: Write Service Account Key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > sa-key.json

    # Authenticate with GCP using the Service Account Key
    - name: Authenticate with GCP
      run: gcloud auth activate-service-account --key-file=sa-key.json

    # Verify Active Account
    - name: Verify Active Account
      run: gcloud auth list

    # Set GCP Project
    - name: Set GCP Project
      run: gcloud config set project my-kubernetes-project-438008

    # Install gke-gcloud-auth-plugin via apt-get
    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

    # Access GKE Cluster
    - name: Access GKE Cluster
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials vector-cluster \
          --region us-central1-a \
          --project my-kubernetes-project-438008

    # Apply Kubernetes YAML Configuration
    - name: Apply Kubernetes Configuration
      run: |
        kubectl apply -f k8s/

    # Verify Deployment
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get hpa
